import React from "react";
import logo from "../assets/Logo.png";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope,faUser} from "@fortawesome/free-solid-svg-icons";

export default function Footer() {
  return (
    <section className="foot flex justify-center items-center ">
        <div className="out w-full h-[30vh] flex justify-center items-center">
      <div className="f main  text-center md:text-[1.5rem] flex flex-row justify-center items-center text-[#ffffff] w-[90%] h-full">
        Disclaimer:The developers are not responsible for any incorrect data generated by AI.
      </div>
      </div>
    </section>
  );
}
